<?php

namespace Container22Z3xxp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OHz634KService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OHz634K' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OHz634K'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\RoleController::index' => ['privates', '.service_locator.LFjXlKs', 'get_ServiceLocator_LFjXlKsService', true],
            'App\\Controller\\UserController::delete' => ['privates', '.service_locator.yVvQ1jo', 'get_ServiceLocator_YVvQ1joService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.yVvQ1jo', 'get_ServiceLocator_YVvQ1joService', true],
            'App\\Controller\\UserController::exl' => ['privates', '.service_locator.1p9Sgxm', 'get_ServiceLocator_1p9SgxmService', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator.PpkbI7b', 'get_ServiceLocator_PpkbI7bService', true],
            'App\\Controller\\UserController::new' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\RoleController:index' => ['privates', '.service_locator.LFjXlKs', 'get_ServiceLocator_LFjXlKsService', true],
            'App\\Controller\\UserController:delete' => ['privates', '.service_locator.yVvQ1jo', 'get_ServiceLocator_YVvQ1joService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.yVvQ1jo', 'get_ServiceLocator_YVvQ1joService', true],
            'App\\Controller\\UserController:exl' => ['privates', '.service_locator.1p9Sgxm', 'get_ServiceLocator_1p9SgxmService', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator.PpkbI7b', 'get_ServiceLocator_PpkbI7bService', true],
            'App\\Controller\\UserController:new' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\RoleController::index' => '?',
            'App\\Controller\\UserController::delete' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Controller\\UserController::exl' => '?',
            'App\\Controller\\UserController::index' => '?',
            'App\\Controller\\UserController::new' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\RoleController:index' => '?',
            'App\\Controller\\UserController:delete' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'App\\Controller\\UserController:exl' => '?',
            'App\\Controller\\UserController:index' => '?',
            'App\\Controller\\UserController:new' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
