<?php

namespace Container22Z3xxp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserWithWeatherService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\UserWithWeather' shared autowired service.
     *
     * @return \App\Service\UserWithWeather
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/UserWithWeather.php';

        return $container->privates['App\\Service\\UserWithWeather'] = new \App\Service\UserWithWeather(($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')));
    }
}
