<?php

namespace Container22Z3xxp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUnloadUserToExcelCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\UnloadUserToExcelCommand' shared autowired service.
     *
     * @return \App\Command\UnloadUserToExcelCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/UnloadUserToExcelCommand.php';

        $container->privates['App\\Command\\UnloadUserToExcelCommand'] = $instance = new \App\Command\UnloadUserToExcelCommand(\dirname(__DIR__, 4), ($container->privates['App\\Service\\UnloadUserToExcel'] ?? $container->load('getUnloadUserToExcelService')));

        $instance->setName('app:usertoexcel');
        $instance->setDescription('Команда по выгрузке пользователей в excel');

        return $instance;
    }
}
