<?php

namespace ContainerOuuzM5n;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsole_Command_PublicAlias_Mybuilder_CronosBundle_Command_DumpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'console.command.public_alias.mybuilder.cronos_bundle.command.dump' shared service.
     *
     * @return \MyBuilder\Bundle\CronosBundle\Command\DumpCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/dependency-injection/ContainerAwareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/dependency-injection/ContainerAwareTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/mybuilder/cronos-bundle/Command/CommandBase.php';
        include_once \dirname(__DIR__, 4).'/vendor/mybuilder/cronos-bundle/Command/DumpCommand.php';

        return $container->services['console.command.public_alias.mybuilder.cronos_bundle.command.dump'] = new \MyBuilder\Bundle\CronosBundle\Command\DumpCommand();
    }
}
