<?php

namespace ContainerOuuzM5n;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMybuilder_CronosBundle_AnnotationCronExporterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'mybuilder.cronos_bundle.annotation_cron_exporter' shared service.
     *
     * @return \MyBuilder\Bundle\CronosBundle\Exporter\AnnotationCronExporter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/mybuilder/cronos-bundle/Exporter/AnnotationCronExporter.php';

        $container->services['mybuilder.cronos_bundle.annotation_cron_exporter'] = $instance = new \MyBuilder\Bundle\CronosBundle\Exporter\AnnotationCronExporter(($container->privates['annotations.cached_reader'] ?? self::getAnnotations_CachedReaderService($container)));

        $instance->setConfig($container->parameters['mybuilder.cronos_bundle.exporter_config']);

        return $instance;
    }
}
