<?php

namespace ContainerOuuzM5n;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUnloadUserToExcelService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\UnloadUserToExcel' shared autowired service.
     *
     * @return \App\Service\UnloadUserToExcel
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/UnloadUserToExcel.php';

        return $container->privates['App\\Service\\UnloadUserToExcel'] = new \App\Service\UnloadUserToExcel(\dirname(__DIR__, 4), ($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')));
    }
}
