<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container22Z3xxp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container22Z3xxp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container22Z3xxp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container22Z3xxp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container22Z3xxp\App_KernelDevDebugContainer([
    'container.build_hash' => '22Z3xxp',
    'container.build_id' => '054a9ef2',
    'container.build_time' => 1690349928,
], __DIR__.\DIRECTORY_SEPARATOR.'Container22Z3xxp');
